### PR TITLE
chore(dbt-sync): Allow the specification of dbt models using their path

### PR DESCRIPTION
**Pull request by Vitor-Avila**
This PR adds the ability to specify the models that should be synced using their relative path. Both specifying files (for example `--select models/my_model.sql`) and folders (for example `--select models/prod`) work. When selecting a folder, it supports the inclusion or not of the last trailing slash(`--select models/prod == --select models/prod/`). 

It's also possible to use `*` after the folder name, however for this approach it's required to pass the argument as a string -> `--select "models/prod/*"` otherwise the terminal automatically creates one argument per file, breaking the CLI.

Implements https://github.com/preset-io/backend-sdk/issues/217 and https://github.com/preset-io/backend-sdk/issues/171.

### CODE REVIEW

**Comment by dweaver33** [comment]
Would this allow us to pass the file list like this?

`--select models/my_model.sql models/my_model2.sql models/my_model3.sql`

**Comment by Vitor-Avila** [comment]
> Would this allow us to pass the file list like this?
> 
> `--select models/my_model.sql models/my_model2.sql models/my_model3.sql`

@dweaver33 not really, you would have to add one `--select` tag per file, or combine the files in a directory and use the directory instead:

``` bash
--select models/my_model.sql --select models/my_model2.sql --select models/my_model3.sql
```

**Comment by dweaver33** [comment]
> > Would this allow us to pass the file list like this?
> > `--select models/my_model.sql models/my_model2.sql models/my_model3.sql`
> 
> @dweaver33 not really, you would have to add one `--select` tag per file, or combine the files in a directory and use the directory instead:
> 
> ```shell
> --select models/my_model.sql --select models/my_model2.sql --select models/my_model3.sql
> ```

Ah, ok.  I think I can work with this limitation.

**Review by betodealmeida — APPROVED** [review]
This is awesome!

**Comment by dweaver33** [comment]
@Vitor-Avila, what's the timeline for cutting a release with this PR in it?  We are eagerly awaiting.  😄

**Comment by Vitor-Avila** [comment]
@dweaver33 wait no more! Just released version `0.2.8` including this change. Let me know if you face any issues to use this functionality.

**Comment by dweaver33** [comment]
Thank you!  We'll be testing over the next few weeks

**Pull request merged**
