### PR TITLE
feat: check DB connectivity before import

### PR DESCRIPTION
**Pull request by betodealmeida**
Before running an import with `superset sync native` test the DB connectivity and warn if it fails (failure could be expected, depending on the network configuration).

### CODE REVIEW

**Comment by cwegener** [comment]
Works nicely! Just noticed it when I updated to latest master today. Got slightly startled on first Warning but was happy that the import completed successfully!

**Comment by betodealmeida** [comment]
> Works nicely! Just noticed it when I updated to latest master today. Got slightly startled on first Warning but was happy that the import completed successfully!

Nice! Yeah, I was expecting valid cases where this would fail as expected... but it really helps debugging in other cases.

**Comment by cwegener** [comment]
One thing I forgot to mention:

The WARNING Log message does include the cleartext password in the SQLAlchemy Engine URI.

I guess that would be an easy thing to fix?

**Comment by betodealmeida** [comment]
> One thing I forgot to mention:
> 
> The WARNING Log message does include the cleartext password in the SQLAlchemy Engine URI.
> 
> I guess that would be an easy thing to fix?

Oh, thanks for letting me know! That's not good, I'll fix it... I thought SQLAlchemy masked the password, I think I need to explicitly convert it to a string.

**Pull request merged**
